# Site settings
title: Jasmin Rubinovitz
email: jasrub@gmail.com
description: Jasmin Rubinovitz - Computer Science Researcher Artist and Designer
baseurl:  # the subpath of your site, e.g. /blog/
url: jasrub.github.io
# twitter_username: twitter_username
# github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"
redirects: yes

collections:
  portfolio:
    output: true
    permalink: /projects/:path/
