url: https://jasrub.github.io
baseurl: 

# Site settings
title: Jasmin Rubinovitz
email: jasrub@gmail.com
description: "Jasmin Rubinovitz - A Researcher Computer Sceintist Artist and Designer"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 96CED2
  secondary: 258990
  secondary-dark: 333

Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://il.linkedin.com/pub/jasmin-rubinovitz/a5/a91/9b1
  - title: facebook
    url: https://www.facebook.com/jasmin.rubinovitz
  - title: github
    url: https://github.com/jasrub

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty